# Ejercicio FIFA

## Diestros vs Zurdos

¿Te acuerdas del famoso problema de los diestros y los zurdos? Como vimos, con un algoritmo lineal no era posible predecir demasiado bien si un jugador era zurdo o diestro. Con el modelo basado en árboles de decisión, mejorábamos nuestro porcentaje de acierto (con los datos equilibrados).

1. Implementa el caso con un modelo KNN. ¿Conseguirás un mejor score (con datos balanceados) que con el modelo basado en árboles de decisión? Puedes crear todas las variables que quieras, al igual que hemos hecho para los otros modelos:

In [2]:
import pandas as pd

df = pd.read_csv("../../../data/FIFA20.csv")
df

,short_name,long_name,dob,club,overall,potential,value_eur,wage_eur,team_position,preferred_foot,influencer
0,L. Messi,Lionel Andrés Messi Cuccittini,1987-06-24,FC Barcelona,94,94,95500000,565000,RW,Left,True
1,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,1985-02-05,Juventus,93,93,58500000,405000,LW,Right,True
2,Neymar Jr,Neymar da Silva Santos Junior,1992-02-05,Paris Saint-Germain,92,92,105500000,290000,CAM,Right,True
3,J. Oblak,Jan Oblak,1993-01-07,Atlético Madrid,91,93,77500000,125000,GK,Right,False
4,E. Hazard,Eden Hazard,1991-01-07,Real Madrid,91,91,90000000,470000,LW,Right,True
...,...,...,...,...,...,...,...,...,...,...,...
18273,Shao Shuai,邵帅,1997-03-10,Beijing Renhe FC,48,56,40000,2000,RES,Right,False
18274,Xiao Mingjie,Mingjie Xiao,1997-01-01,Shanghai SIPG FC,48,56,40000,2000,SUB,Right,False
18275,Zhang Wei,张威,2000-05-16,Hebei China Fortune FC,48,56,40000,1000,SUB,Right,False
18276,Wang Haijian,汪海健,2000-08-02,Shanghai Greenland Shenhua FC,48,54,40000,1000,SUB,Right,False
18277,Pan Ximing,潘喜明,1993-01-11,Hebei China Fortune FC,48,51,40000,2000,SUB,Right,False